### ISSUE TITLE
Changes to support spec `v0.6.0`, `v0.7.0` compliance

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk#126] opened 2023-05-16 16:50 UTC
## Implement specification v0.7.0 changes

See [changes since last release](https://github.com/open-feature/spec/compare/v0.5.2...v0.7.0).

Please note there's no need to complete all these tasks in a single PR (in fact, that's not recommended).

### Functional requirements:

- [ ] implement flag metadata: https://github.com/open-feature/spec/commit/74c373e089ad77bf8cac84f3d93c00c945ff3a8a
- [x] open-feature/dotnet-sdk#131
  - [x] open-feature/spec#192 
- [x] implement init/shutdown (done with https://github.com/open-feature/dotnet-sdk/pull/158)
- [x] implement events: https://openfeature.dev/specification/sections/events
- [ ] #165

### Non-functional requirements:

- [ ] add relevant tests
- [ ] add examples and documentation, see template README
- [ ] update specification badge to `v0.7.0`: [![Specification](https://img.shields.io/static/v1?label=Specification&message=v0.7.0&color=yellow)](https://github.com/open-feature/spec/tree/v0.7.0)

### Keep in mind:

- backwards compatibility is _highly encouraged_
  - take every precaution to ensure existing code written by _application authors_ and existing providers implementations, do not break
- it's recommended these features are released together

**Comment by askpt** [comment] 2024-01-18 18:57
Closing this issue since it's a duplicate of https://github.com/open-feature/dotnet-sdk/milestone/1

**Closed by askpt** 2024-01-18 18:57 UTC
Labels: help wanted, v0.6.0, v0.7.0
